"""empty message

Revision ID: 216374691361
Revises: c5ef166bec70
Create Date: 2025-05-08 21:49:12.360766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216374691361'
down_revision = 'c5ef166bec70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
