"""empty message

Revision ID: 550aa709e32a
Revises: bfff2ff677b9
Create Date: 2025-05-03 21:24:17.410952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550aa709e32a'
down_revision = 'bfff2ff677b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
